
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.5.0
 * Query Engine version: 280c870be64f457428992c43c1f6d557fab6e29e
 */
Prisma.prismaVersion = {
  client: "7.5.0",
  engine: "280c870be64f457428992c43c1f6d557fab6e29e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  realName: 'realName',
  role: 'role',
  isActive: 'isActive',
  mustChangePass: 'mustChangePass',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sortOrder: 'sortOrder',
  isActive: 'isActive'
};

exports.Prisma.AssetTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deviceType: 'deviceType',
  brand: 'brand',
  model: 'model',
  os: 'os',
  cpu: 'cpu',
  memory: 'memory',
  storage: 'storage',
  remark: 'remark',
  isActive: 'isActive',
  sortOrder: 'sortOrder'
};

exports.Prisma.AssetScalarFieldEnum = {
  id: 'id',
  assetCode: 'assetCode',
  templateId: 'templateId',
  deviceType: 'deviceType',
  brand: 'brand',
  model: 'model',
  serialNumber: 'serialNumber',
  os: 'os',
  cpu: 'cpu',
  memory: 'memory',
  storage: 'storage',
  status: 'status',
  currentUserName: 'currentUserName',
  departmentId: 'departmentId',
  purchaseDate: 'purchaseDate',
  warrantyExpiry: 'warrantyExpiry',
  remark: 'remark',
  version: 'version'
};

exports.Prisma.AssetRecordScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  action: 'action',
  userName: 'userName',
  departmentId: 'departmentId',
  actionDate: 'actionDate',
  expectedReturnDate: 'expectedReturnDate',
  proofImage: 'proofImage',
  remark: 'remark',
  operatorId: 'operatorId',
  requestId: 'requestId',
  createdAt: 'createdAt'
};

exports.Prisma.RepairRecordScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  faultDescription: 'faultDescription',
  repairVendor: 'repairVendor',
  repairCost: 'repairCost',
  repairResult: 'repairResult',
  startDate: 'startDate',
  endDate: 'endDate',
  remark: 'remark'
};

exports.Prisma.SystemConfigScalarFieldEnum = {
  configKey: 'configKey',
  configValue: 'configValue',
  description: 'description',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.OperationLogScalarFieldEnum = {
  id: 'id',
  operatorId: 'operatorId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  detail: 'detail',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.Role = exports.$Enums.Role = {
  super_admin: 'super_admin',
  admin: 'admin',
  viewer: 'viewer'
};

exports.DeviceType = exports.$Enums.DeviceType = {
  laptop: 'laptop',
  desktop: 'desktop',
  aio: 'aio',
  server: 'server'
};

exports.AssetStatus = exports.$Enums.AssetStatus = {
  in_stock: 'in_stock',
  waiting_pickup: 'waiting_pickup',
  in_use: 'in_use',
  borrowed: 'borrowed',
  in_repair: 'in_repair',
  retired: 'retired'
};

exports.AssetRecordAction = exports.$Enums.AssetRecordAction = {
  stock_in: 'stock_in',
  assign: 'assign',
  cancel_assign: 'cancel_assign',
  pick_up: 'pick_up',
  check_out: 'check_out',
  lend: 'lend',
  return: 'return',
  transfer: 'transfer',
  repair: 'repair',
  repair_done: 'repair_done',
  retire: 'retire'
};

exports.RepairResult = exports.$Enums.RepairResult = {
  fixed: 'fixed',
  unfixable: 'unfixable'
};

exports.Prisma.ModelName = {
  User: 'User',
  Department: 'Department',
  AssetTemplate: 'AssetTemplate',
  Asset: 'Asset',
  AssetRecord: 'AssetRecord',
  RepairRecord: 'RepairRecord',
  SystemConfig: 'SystemConfig',
  OperationLog: 'OperationLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
